# Generated by Django 5.1.5 on 2025-02-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('num', models.CharField(max_length=10)),
                ('prompt', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis', models.TextField()),
                ('img', models.URLField()),
                ('original', models.TextField()),
                ('shorten', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
